services:
  app:
    image: noozecrypt/stay-ease:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stay-ease
      SPRING_DATASOURCE_USERNAME: stay-ease
      SPRING_DATASOURCE_PASSWORD: stay-ease
      SPRING_DOCKER_COMPOSE_ENABLED: false
    depends_on:
      - db

  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: stay-ease
      POSTGRES_USER: stay-ease
      POSTGRES_PASSWORD: stay-ease
    ports:
      - "5432:5432"